version: '3.8'

services:
  frontend:
    build:
      context: .
      args:
        - VITE_API_URL=${VITE_API_URL}
    networks:
      - app-network
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy

networks:
  app-network:
    external: true